### ISSUE TITLE
Delete Empty target-groups (which are assigned to load balancer)

### ISSUE THREAD

**Issue by RogerSik** [Signiant/aws-target-group-cleanup#2]
Is there a way to auto delete empty target-groups which are assigned to load balancer?

**Comment by haggaret** [comment]
Hey @RogerSik - sorry for the late reply on this. I don't think there is a way to auto delete empty target groups, or else we wouldn't have needed this. That being said, it's possible that AWS has added that feature since we wrote this. I haven't investigated though.

**Comment by RogerSik** [comment]
Hey @haggaret i think i wrote it wrong. Your script delete empty aws-target-group which are not assigned to a load balancer.

I would like to delete with your script empty aws-target-groups which **are** assigned to a load balancer.

**Comment by haggaret** [comment]
@RogerSik My apologies, I definitely misunderstood. 🙂 I would think that would be pretty easy to add - if I get a chance a little later, I can have a look at it.
